<template><div><h1 id="the-faq-s-section" tabindex="-1"><a class="header-anchor" href="#the-faq-s-section"><span>The FAQ's Section</span></a></h1>
<h2 id="q-how-do-i-install-the-tor-w-mod" tabindex="-1"><a class="header-anchor" href="#q-how-do-i-install-the-tor-w-mod"><span><font color=cyan>Q: How do I install the TOR-W mod?</font></span></a></h2>
<p>A: You don’t need to install anything for the TOR-W mod if you’re a player. Since it’s a host-only mod, as long as the host has it enabled, everyone can enjoy the new content without having to download anything. But if you need help with setting it up, see the <RouteLink to="/install.html">Install</RouteLink> page.</p>
<h2 id="q-what-does-tor-w-stand-for-and-what-s-different-about-this-mod" tabindex="-1"><a class="header-anchor" href="#q-what-does-tor-w-stand-for-and-what-s-different-about-this-mod"><span><font color=purple>Q: What does TOR-W stand for, and what’s different about this mod?</font></span></a></h2>
<p>A: TOR-W stands for Town Of Re-Worked. It adds new roles and gamplay mechanics, making the gameplay more exciting and unpredictable while keeping the core Among Us experience intact.</p>
<h2 id="q-do-players-need-to-install-the-mod-too-or-only-the-host" tabindex="-1"><a class="header-anchor" href="#q-do-players-need-to-install-the-mod-too-or-only-the-host"><span><font color=red>Q: Do players need to install the mod too, or only the host?</font></span></a></h2>
<p>A: Only the host needs to have the mod installed. As long as the host is running TOR-W, everyone in the lobby will be able to experience the new features automatically.</p>
<h2 id="q-what-new-roles-or-abilities-does-the-tor-w-mod-add" tabindex="-1"><a class="header-anchor" href="#q-what-new-roles-or-abilities-does-the-tor-w-mod-add"><span><font color=lime>Q: What new roles or abilities does the TOR-W mod add?</font></span></a></h2>
<p>A: TOR-W introduces several new roles from the <b><a href="https://discord.gg/HczqtuBfcu" style="color:purple">TOR-W Discord Server</a></b>, each with unique abilities. For example, you might find a role that can manipulate time or cast spells to sabotage or protect crewmates. There are also new impostor tricks and ways for crewmates to defend themselves.</p>
<h2 id="q-are-there-any-new-visual-or-sound-effects-unique-to-this-mod" tabindex="-1"><a class="header-anchor" href="#q-are-there-any-new-visual-or-sound-effects-unique-to-this-mod"><span><font color=pink>Q: Are there any new visual or sound effects unique to this mod?</font></span></a></h2>
<p>A: Yes and No. TOR-W comes with some custom sound effects that bring the atmosphere into the game. It only works for the host, and if you have the mod installed, with the host.</p>
<h2 id="q-does-the-mod-change-the-number-of-impostors-or-crew-size" tabindex="-1"><a class="header-anchor" href="#q-does-the-mod-change-the-number-of-impostors-or-crew-size"><span><font color=yellow>Q: Does the mod change the number of Impostors or Crew size?</font></span></a></h2>
<p>A: The number of Impostors and Crew size can be adjusted like normal, but the mod allows for more flexibility in role assignments and game balance. Some roles from TOR-W might tilt the odds in favor of either side depending on how they’re used.</p>
<h2 id="q-are-there-any-specific-settings-the-host-needs-to-enable-for-tor-w" tabindex="-1"><a class="header-anchor" href="#q-are-there-any-specific-settings-the-host-needs-to-enable-for-tor-w"><span><font color=amber>Q: Are there any specific settings the host needs to enable for TOR-W?</font></span></a></h2>
<p>A: The mod has a few custom settings to enhance the TOR-W experience. Make sure to review the mod settings menu before starting the game, where you can adjust role distributions and enable specific abilities that fit your lobby’s playstyle.</p>
<h2 id="q-is-this-mod-compatible-with-other-mods-or-standard-among-us-updates" tabindex="-1"><a class="header-anchor" href="#q-is-this-mod-compatible-with-other-mods-or-standard-among-us-updates"><span><font color=gray>Q: Is this mod compatible with other mods or standard Among Us updates?</font></span></a></h2>
<p>A: TOR-W is designed to work with the base game, but it may not be compatible with other mods that alter game mechanics. After Among Us updates, the mod might need a quick patch, so keep an eye on updates to ensure everything runs smoothly.</p>
<h2 id="q-does-tor-w-affect-the-map-layout-or-add-new-maps" tabindex="-1"><a class="header-anchor" href="#q-does-tor-w-affect-the-map-layout-or-add-new-maps"><span><font color=#008b8b>Q: Does TOR-W affect the map layout or add new maps?</font></span></a></h2>
<p>A: TOR-W doesn’t introduce any new maps but does not modify existing ones. All the maps are not tweakable with a Host-Only mod, only when everyone uses a mod, such as Submerged, for example.</p>
</div></template>


